//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketReporting
    {
        public int BucketId { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public int Entities { get; set; }
        public int NumberCallingBuckets { get; set; }
        public string CallingBuckets { get; set; }
        public int NumberCalleduckets { get; set; }
        public string CalledBuckets { get; set; }
        public int NumberInternalInterfaces { get; set; }
        public int NumberExternalInterfaces { get; set; }
    }
}
