//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HousingSAModel : DbContext
    {
        public HousingSAModel()
            : base("name=HousingSAModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AuditLog> AuditLogs { get; set; }
        public DbSet<Entity> Entities { get; set; }
        public DbSet<EntityOwnershipStrength> EntityOwnershipStrengths { get; set; }
        public DbSet<EntityRelationship> EntityRelationships { get; set; }
        public DbSet<Interface> Interfaces { get; set; }
        public DbSet<InternalInterface> InternalInterfaces { get; set; }
        public DbSet<TableDefinition> TableDefinitions { get; set; }
        public DbSet<ProcedureDefinition> ProcedureDefinitions { get; set; }
        public DbSet<Bucket> Buckets { get; set; }
        public DbSet<TableDefinitions1> TableDefinitions1 { get; set; }
        public DbSet<TransactionDefinition> TransactionDefinitions { get; set; }
        public DbSet<TriggerDefinitions1> TriggerDefinitions1 { get; set; }
        public DbSet<RuleDefinition> RuleDefinitions { get; set; }
        public DbSet<TriggerDefinition> TriggerDefinitions { get; set; }
    }
}
