//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAASModel : DbContext
    {
        public FAASModel()
            : base("name=FAASModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<LanguageReference> LanguageReferences { get; set; }
        public DbSet<PhaseReference> PhaseReferences { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Record> Records { get; set; }
        public DbSet<Snapshot> Snapshots { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<AuditLog> AuditLogs { get; set; }
        public DbSet<Bucket> Buckets { get; set; }
        public DbSet<BucketConnection> BucketConnections { get; set; }
        public DbSet<BucketReporting> BucketReportings { get; set; }
        public DbSet<Entity> Entities { get; set; }
        public DbSet<EntityOwnershipStrength> EntityOwnershipStrengths { get; set; }
        public DbSet<EntityRelationship> EntityRelationships { get; set; }
        public DbSet<EntityResidence> EntityResidences { get; set; }
        public DbSet<Interface> Interfaces { get; set; }
        public DbSet<InterfaceReporting> InterfaceReportings { get; set; }
        public DbSet<InternalInterface> InternalInterfaces { get; set; }
        public DbSet<FunctionDefinition> FunctionDefinitions { get; set; }
        public DbSet<PackageDefinition> PackageDefinitions { get; set; }
        public DbSet<RuleDefinition> RuleDefinitions { get; set; }
        public DbSet<TableDefinition> TableDefinitions { get; set; }
        public DbSet<TableForeignConstraint> TableForeignConstraints { get; set; }
        public DbSet<TransactionDefinition> TransactionDefinitions { get; set; }
        public DbSet<TriggerDefinition> TriggerDefinitions { get; set; }
    }
}
