//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentationLogic
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int RecordId { get; set; }
        public string Annotation { get; set; }
        public string AnnotationType { get; set; }
        public Nullable<int> BuildRuleId { get; set; }
        public string Description { get; set; }
        public string PFKey { get; set; }
        public Nullable<int> PFKeyRuleId { get; set; }
    
        public virtual Record Record { get; set; }
    }
}
