//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDefinition
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string BuildRule { get; set; }
        public string Description { get; set; }
        public string PFKey { get; set; }
        public string PFKeyRule { get; set; }
        public string Unit { get; set; }
    }
}
