//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerDefinitions1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string TriggeringEvent { get; set; }
        public string TableName { get; set; }
        public string WhenClause { get; set; }
        public string Body { get; set; }
        public string Unit { get; set; }
        public string BaseObjectType { get; set; }
    }
}
