//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Import
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerDefinition
    {
        public int Id { get; set; }
        public int TableSourceId { get; set; }
        public string TableName { get; set; }
        public int RuleSourceId { get; set; }
        public string RuleName { get; set; }
        public string Access { get; set; }
        public string Unit { get; set; }
    }
}
