//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public Entity()
        {
            this.Interfaces = new HashSet<Interface>();
            this.InterfaceReportings = new HashSet<InterfaceReporting>();
            this.InternalInterfaces = new HashSet<InternalInterface>();
        }
    
        public int Id { get; set; }
        public int SourceId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string SourceUnit { get; set; }
        public string NormalisedUnit { get; set; }
    
        public virtual EntityResidence EntityResidence { get; set; }
        public virtual ICollection<Interface> Interfaces { get; set; }
        public virtual ICollection<InterfaceReporting> InterfaceReportings { get; set; }
        public virtual ICollection<InternalInterface> InternalInterfaces { get; set; }
    }
}
