//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interface
    {
        public Interface()
        {
            this.InterfaceReportings = new HashSet<InterfaceReporting>();
        }
    
        public int Id { get; set; }
        public string TargetUnit { get; set; }
        public string EntityRelationshipIds { get; set; }
        public int TargetEntityId { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual ICollection<InterfaceReporting> InterfaceReportings { get; set; }
    }
}
