//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDefinition
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string FieldSyntax { get; set; }
        public Nullable<int> FieldLength { get; set; }
        public Nullable<int> FieldDecimal { get; set; }
        public Nullable<int> FieldNumber { get; set; }
        public string KeyType { get; set; }
        public string TableType { get; set; }
        public string Unit { get; set; }
    }
}
